import React from 'react';

const ProductionReport = () => {
  return (
    <div className="container">
      <h1>Production Report - Week of Apr 21, 2026</h1>

      <div style={{ display: 'flex', gap: '15px', marginBottom: '20px' }}>
        <button className="btn-primary">PDF</button>
        <button className="btn-primary">Email</button>
        <button className="btn-secondary">Print</button>
      </div>

      <div style={{ padding: '15px', background: '#f5f5f5', borderRadius: '8px', marginBottom: '20px' }}>
        <p><strong>Report Date:</strong> Apr 21-27, 2026</p>
        <p><strong>Generated By:</strong> Production Manager Dashboard</p>
        <p><strong>Status:</strong> Final Report</p>
      </div>

      <h2>Production Summary</h2>
      <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr 1fr',
        gap: '15px',
        marginBottom: '20px'
      }}>
        <div style={{ padding: '15px', background: '#e6f7e6', borderRadius: '8px' }}>
          <p style={{ fontSize: '12px', color: '#666', marginBottom: '5px' }}>Target</p>
          <p style={{ fontSize: '24px', fontWeight: 'bold', color: '#2CA02C' }}>38,500 L</p>
        </div>
        <div style={{ padding: '15px', background: '#e6f7e6', borderRadius: '8px' }}>
          <p style={{ fontSize: '12px', color: '#666', marginBottom: '5px' }}>Actual</p>
          <p style={{ fontSize: '24px', fontWeight: 'bold', color: '#2CA02C' }}>37,200 L</p>
        </div>
        <div style={{ padding: '15px', background: '#fff5e6', borderRadius: '8px' }}>
          <p style={{ fontSize: '12px', color: '#666', marginBottom: '5px' }}>Variance</p>
          <p style={{ fontSize: '24px', fontWeight: 'bold', color: '#FF7F0E' }}>-3.4%</p>
        </div>
      </div>

      <h2>Production by Product</h2>
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th>Target (L)</th>
            <th>Actual (L)</th>
            <th>Variance</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Vanilla</td>
            <td>16,000</td>
            <td>15,600</td>
            <td>-2.5%</td>
            <td><span className="status-badge status-ok">✓ OK</span></td>
          </tr>
          <tr>
            <td>Caramel</td>
            <td>12,000</td>
            <td>11,800</td>
            <td>-1.7%</td>
            <td><span className="status-badge status-ok">✓ OK</span></td>
          </tr>
          <tr>
            <td>Mint</td>
            <td>10,500</td>
            <td>9,800</td>
            <td>-6.7%</td>
            <td><span className="status-badge" style={{ background: '#fff5e6', color: '#FF7F0E' }}>⚠ Below</span></td>
          </tr>
        </tbody>
      </table>

      <h2>Production Efficiency</h2>
      <div style={{ padding: '15px', background: '#f9f9f9', borderRadius: '8px' }}>
        <p><strong>Line 1 Utilization:</strong> 82% (as planned) ✓</p>
        <p style={{ marginTop: '8px' }}><strong>Line 2 Utilization:</strong> 65% (low - investigate)</p>
        <p style={{ marginTop: '8px' }}><strong>Line 3 Utilization:</strong> 89% (above planned)</p>
        <p style={{ marginTop: '8px' }}><strong>Changeover Time:</strong> 24h total (4 x 6h) = as expected</p>
        <p style={{ marginTop: '8px' }}><strong>Equipment Downtime:</strong> 0h (no breakdowns)</p>
        <p style={{ marginTop: '8px' }}><strong>Quality Pass Rate:</strong> 98.7% (batches passed QC)</p>
      </div>

      <h2>Key Issues</h2>
      <div style={{ marginTop: '15px' }}>
        <div style={{
          padding: '12px',
          borderRadius: '4px',
          borderLeft: '4px solid #FF7F0E',
          background: '#fff5e6',
          marginBottom: '10px'
        }}>
          <strong style={{ color: '#FF7F0E' }}>1. Mint production below target (6.7% gap)</strong>
          <p style={{ fontSize: '13px', marginTop: '5px', color: '#663300' }}>
            Cause: Raw material delay Apr 24-25<br />
            Impact: Distributor delay on HoReCa channel
          </p>
        </div>

        <div style={{
          padding: '12px',
          borderRadius: '4px',
          borderLeft: '4px solid #FF7F0E',
          background: '#fff5e6',
          marginBottom: '10px'
        }}>
          <strong style={{ color: '#FF7F0E' }}>2. Line 2 utilization low (65% vs 75% planned)</strong>
          <p style={{ fontSize: '13px', marginTop: '5px', color: '#663300' }}>
            Cause: Caramel demand lower than forecast<br />
            Action: Reduce Caramel production allocation
          </p>
        </div>
      </div>

      <h2>Inventory Impact</h2>
      <div style={{ padding: '15px', background: '#f9f9f9', borderRadius: '8px', marginTop: '15px' }}>
        <p><strong>Produced:</strong> 37,200 L</p>
        <p style={{ marginTop: '8px' }}><strong>Distributed:</strong> 35,600 L</p>
        <p style={{ marginTop: '8px' }}><strong>Ending Inventory:</strong> 12,800 L (vs 15,000 L planned)</p>
        <p style={{ marginTop: '8px' }}><strong>Cold Chain Cost:</strong> $42,500 (electricity + storage)</p>
      </div>

      <div style={{ marginTop: '20px', display: 'flex', gap: '10px' }}>
        <button className="btn-primary">Sign Off</button>
        <button className="btn-secondary">Share with Team</button>
      </div>
    </div>
  );
};

export default ProductionReport;
